// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject1
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// This method starts App
        /// </summary>
        public void StartAppRecordedMethod()
        {

            // Launch '%USERPROFILE%\Desktop\Calculator2.exe'
            ApplicationUnderTest calculator2Application = ApplicationUnderTest.Launch(this.StartAppRecordedMethodParams.ExePath, this.StartAppRecordedMethodParams.AlternateExePath);
        }
        
        /// <summary>
        /// Method closes App
        /// </summary>
        public void CloseAppRecordedMethod()
        {
            #region Variable Declarations
            WinButton uIЗакрытьButton = this.UIForm1Window.UIForm1TitleBar.UIЗакрытьButton;
            #endregion

            // Click 'Закрыть' button
            Mouse.Click(uIЗакрытьButton, new Point(33, 14));
        }
        
        /// <summary>
        /// Identification of all elements of the interface
        /// </summary>
        public void InterfeceRecordedMethod()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIForm1Window.UIItem0Window.UIItemEdit;
            WinButton uIItem7Button = this.UIForm1Window.UIForm1Client.UIItem7Button;
            WinButton uIItem4Button = this.UIForm1Window.UIForm1Client.UIItem4Button;
            WinButton uIItem1Button = this.UIForm1Window.UIForm1Client.UIItem1Button;
            WinButton uIItem0Button = this.UIForm1Window.UIForm1Client.UIItem0Button;
            WinButton uIItem8Button = this.UIForm1Window.UIForm1Client.UIItem8Button;
            WinButton uIItem5Button = this.UIForm1Window.UIForm1Client.UIItem5Button;
            WinButton uIItem2Button = this.UIForm1Window.UIForm1Client.UIItem2Button;
            WinButton uIItem9Button = this.UIForm1Window.UIForm1Client.UIItem9Button;
            WinButton uIItem6Button = this.UIForm1Window.UIForm1Client.UIItem6Button;
            WinButton uIItem3Button = this.UIForm1Window.UIForm1Client.UIItem3Button;
            WinButton uICButton = this.UIForm1Window.UIForm1Client.UICButton;
            WinButton uIItemButton = this.UIForm1Window.UIForm1Client.UIItemButton;
            WinButton uIItemButton1 = this.UIForm1Window.UIForm1Client.UIItemButton1;
            WinButton uIItemButton2 = this.UIForm1Window.UIForm1Client.UIItemButton2;
            WinButton uIItemButton3 = this.UIForm1Window.UIForm1Client.UIItemButton3;
            WinButton uIItemButton4 = this.UIForm1Window.UIForm1Client.UIItemButton4;
            #endregion

            // Click text box
            Mouse.Click(uIItemEdit, new Point(85, 14));

            // Click '7' button
            Mouse.Click(uIItem7Button, new Point(16, 12));

            // Click '4' button
            Mouse.Click(uIItem4Button, new Point(15, 5));

            // Click '1' button
            Mouse.Click(uIItem1Button, new Point(18, 13));

            // Click '0' button
            Mouse.Click(uIItem0Button, new Point(22, 11));

            // Click '8' button
            Mouse.Click(uIItem8Button, new Point(23, 17));

            // Click '5' button
            Mouse.Click(uIItem5Button, new Point(21, 9));

            // Click '2' button
            Mouse.Click(uIItem2Button, new Point(18, 10));

            // Click '9' button
            Mouse.Click(uIItem9Button, new Point(25, 16));

            // Click '6' button
            Mouse.Click(uIItem6Button, new Point(16, 16));

            // Click '3' button
            Mouse.Click(uIItem3Button, new Point(16, 11));

            // Click 'C' button
            Mouse.Click(uICButton, new Point(10, 17));

            // Click '+' button
            Mouse.Click(uIItemButton, new Point(19, 15));

            // Click '-' button
            Mouse.Click(uIItemButton1, new Point(16, 8));

            // Click '*' button
            Mouse.Click(uIItemButton2, new Point(17, 10));

            // Click '/' button
            Mouse.Click(uIItemButton3, new Point(20, 19));

            // Click '=' button
            Mouse.Click(uIItemButton4, new Point(22, 16));
        }
        
        /// <summary>
        /// AreEqual9AssertMethod - Use 'AreEqual9AssertMethodExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AreEqual9AssertMethod()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIForm1Window.UIItem0Window.UIItemEdit;
            #endregion

            // Verify that the 'Text' property of text box equals '9'
            Assert.AreEqual(this.AreEqual9AssertMethodExpectedValues.UIItemEditText, uIItemEdit.Text, "Are not Equal \"9\"");
        }
        
        /// <summary>
        /// AdditionTestRecordedMethod
        /// </summary>
        public void AdditionTestRecordedMethod()
        {
            #region Variable Declarations
            WinButton uIItem5Button = this.UIForm1Window.UIForm1Client.UIItem5Button;
            WinButton uIItemButton = this.UIForm1Window.UIForm1Client.UIItemButton;
            WinButton uIItem4Button = this.UIForm1Window.UIForm1Client.UIItem4Button;
            WinButton uIItemButton4 = this.UIForm1Window.UIForm1Client.UIItemButton4;
            #endregion

            // Click '5' button
            Mouse.Click(uIItem5Button, new Point(8, 11));

            // Click '+' button
            Mouse.Click(uIItemButton, new Point(23, 17));

            // Click '4' button
            Mouse.Click(uIItem4Button, new Point(7, 10));

            // Click '=' button
            Mouse.Click(uIItemButton4, new Point(19, 11));
        }
        
        /// <summary>
        /// MultiplicationTestMethod
        /// </summary>
        public void MultiplicationTestMethod()
        {
            #region Variable Declarations
            WinButton uIItem3Button = this.UIForm1Window.UIForm1Client.UIItem3Button;
            WinButton uIItemButton2 = this.UIForm1Window.UIForm1Client.UIItemButton2;
            WinButton uIItemButton4 = this.UIForm1Window.UIForm1Client.UIItemButton4;
            #endregion

            // Click '3' button
            Mouse.Click(uIItem3Button, new Point(14, 21));

            // Click '*' button
            Mouse.Click(uIItemButton2, new Point(16, 13));

            // Click '3' button
            Mouse.Click(uIItem3Button, new Point(8, 13));

            // Click '=' button
            Mouse.Click(uIItemButton4, new Point(18, 16));
        }
        
        /// <summary>
        /// DivisionTestRecordedMethod
        /// </summary>
        public void DivisionTestRecordedMethod()
        {
            #region Variable Declarations
            WinButton uIItem2Button = this.UIForm1Window.UIForm1Client.UIItem2Button;
            WinButton uIItem7Button = this.UIForm1Window.UIForm1Client.UIItem7Button;
            WinButton uIItemButton3 = this.UIForm1Window.UIForm1Client.UIItemButton3;
            WinButton uIItem3Button = this.UIForm1Window.UIForm1Client.UIItem3Button;
            WinButton uIItemButton4 = this.UIForm1Window.UIForm1Client.UIItemButton4;
            #endregion

            // Click '2' button
            Mouse.Click(uIItem2Button, new Point(9, 19));

            // Click '7' button
            Mouse.Click(uIItem7Button, new Point(17, 17));

            // Click '/' button
            Mouse.Click(uIItemButton3, new Point(18, 14));

            // Click '3' button
            Mouse.Click(uIItem3Button, new Point(10, 14));

            // Click '=' button
            Mouse.Click(uIItemButton4, new Point(19, 9));
        }
        
        /// <summary>
        /// SubtractionTestRecordedMethod
        /// </summary>
        public void SubtractionTestRecordedMethod()
        {
            #region Variable Declarations
            WinButton uIItem5Button = this.UIForm1Window.UIForm1Client.UIItem5Button;
            WinButton uIItem9Button = this.UIForm1Window.UIForm1Client.UIItem9Button;
            WinButton uIItemButton1 = this.UIForm1Window.UIForm1Client.UIItemButton1;
            WinButton uIItem0Button = this.UIForm1Window.UIForm1Client.UIItem0Button;
            WinButton uIItemButton4 = this.UIForm1Window.UIForm1Client.UIItemButton4;
            #endregion

            // Click '5' button
            Mouse.Click(uIItem5Button, new Point(14, 16));

            // Click '9' button
            Mouse.Click(uIItem9Button, new Point(15, 17));

            // Click '-' button
            Mouse.Click(uIItemButton1, new Point(14, 20));

            // Click '5' button
            Mouse.Click(uIItem5Button, new Point(15, 17));

            // Click '0' button
            Mouse.Click(uIItem0Button, new Point(40, 20));

            // Click '=' button
            Mouse.Click(uIItemButton4, new Point(17, 21));
        }
        
        /// <summary>
        /// CompareResultsAssertMethod - Use 'CompareResultsAssertMethodExpectedValues' to pass parameters into this method.
        /// </summary>
        public void CompareResultsAssertMethod()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIForm1Window.UIItem0Window.UIItemEdit;
            #endregion

            // Verify that the 'Text' property of text box equals 'Деление на ноль'
            Assert.AreEqual(this.CompareResultsAssertMethodExpectedValues.UIItemEditText, uIItemEdit.Text, "ERROR!");
        }
        
        /// <summary>
        /// DivisionByZeroTestRecordedMethod
        /// </summary>
        public void DivisionByZeroTestRecordedMethod()
        {
            #region Variable Declarations
            WinButton uIItem5Button = this.UIForm1Window.UIForm1Client.UIItem5Button;
            WinButton uIItemButton3 = this.UIForm1Window.UIForm1Client.UIItemButton3;
            WinButton uIItem0Button = this.UIForm1Window.UIForm1Client.UIItem0Button;
            WinButton uIItemButton4 = this.UIForm1Window.UIForm1Client.UIItemButton4;
            #endregion

            // Click '5' button
            Mouse.Click(uIItem5Button, new Point(13, 13));

            // Click '/' button
            Mouse.Click(uIItemButton3, new Point(13, 13));

            // Click '0' button
            Mouse.Click(uIItem0Button, new Point(37, 10));

            // Click '=' button
            Mouse.Click(uIItemButton4, new Point(11, 20));
        }
        
        #region Properties
        public virtual StartAppRecordedMethodParams StartAppRecordedMethodParams
        {
            get
            {
                if ((this.mStartAppRecordedMethodParams == null))
                {
                    this.mStartAppRecordedMethodParams = new StartAppRecordedMethodParams();
                }
                return this.mStartAppRecordedMethodParams;
            }
        }
        
        public virtual AreEqual9AssertMethodExpectedValues AreEqual9AssertMethodExpectedValues
        {
            get
            {
                if ((this.mAreEqual9AssertMethodExpectedValues == null))
                {
                    this.mAreEqual9AssertMethodExpectedValues = new AreEqual9AssertMethodExpectedValues();
                }
                return this.mAreEqual9AssertMethodExpectedValues;
            }
        }
        
        public virtual CompareResultsAssertMethodExpectedValues CompareResultsAssertMethodExpectedValues
        {
            get
            {
                if ((this.mCompareResultsAssertMethodExpectedValues == null))
                {
                    this.mCompareResultsAssertMethodExpectedValues = new CompareResultsAssertMethodExpectedValues();
                }
                return this.mCompareResultsAssertMethodExpectedValues;
            }
        }
        
        public UIForm1Window UIForm1Window
        {
            get
            {
                if ((this.mUIForm1Window == null))
                {
                    this.mUIForm1Window = new UIForm1Window();
                }
                return this.mUIForm1Window;
            }
        }
        #endregion
        
        #region Fields
        private StartAppRecordedMethodParams mStartAppRecordedMethodParams;
        
        private AreEqual9AssertMethodExpectedValues mAreEqual9AssertMethodExpectedValues;
        
        private CompareResultsAssertMethodExpectedValues mCompareResultsAssertMethodExpectedValues;
        
        private UIForm1Window mUIForm1Window;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'StartAppRecordedMethod'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class StartAppRecordedMethodParams
    {
        
        #region Fields
        /// <summary>
        /// Launch '%USERPROFILE%\Desktop\Calculator2.exe'
        /// </summary>
        public string ExePath = "C:\\Users\\Nishik\\Desktop\\Calculator2.exe";
        
        /// <summary>
        /// Launch '%USERPROFILE%\Desktop\Calculator2.exe'
        /// </summary>
        public string AlternateExePath = "%USERPROFILE%\\Desktop\\Calculator2.exe";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AreEqual9AssertMethod'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class AreEqual9AssertMethodExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Text' property of text box equals '9'
        /// </summary>
        public string UIItemEditText = "9";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'CompareResultsAssertMethod'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class CompareResultsAssertMethodExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Text' property of text box equals 'Деление на ноль'
        /// </summary>
        public string UIItemEditText = "Деление на ноль";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIForm1Window : WinWindow
    {
        
        public UIForm1Window()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Form1";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public UIForm1TitleBar UIForm1TitleBar
        {
            get
            {
                if ((this.mUIForm1TitleBar == null))
                {
                    this.mUIForm1TitleBar = new UIForm1TitleBar(this);
                }
                return this.mUIForm1TitleBar;
            }
        }
        
        public UIItem0Window UIItem0Window
        {
            get
            {
                if ((this.mUIItem0Window == null))
                {
                    this.mUIItem0Window = new UIItem0Window(this);
                }
                return this.mUIItem0Window;
            }
        }
        
        public UIForm1Client UIForm1Client
        {
            get
            {
                if ((this.mUIForm1Client == null))
                {
                    this.mUIForm1Client = new UIForm1Client(this);
                }
                return this.mUIForm1Client;
            }
        }
        #endregion
        
        #region Fields
        private UIForm1TitleBar mUIForm1TitleBar;
        
        private UIItem0Window mUIItem0Window;
        
        private UIForm1Client mUIForm1Client;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIForm1TitleBar : WinTitleBar
    {
        
        public UIForm1TitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinButton UIЗакрытьButton
        {
            get
            {
                if ((this.mUIЗакрытьButton == null))
                {
                    this.mUIЗакрытьButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIЗакрытьButton.SearchProperties[WinButton.PropertyNames.Name] = "Закрыть";
                    this.mUIЗакрытьButton.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIЗакрытьButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIЗакрытьButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIItem0Window : WinWindow
    {
        
        public UIItem0Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "0";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIForm1Client : WinClient
    {
        
        public UIForm1Client(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Form1";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinButton UIItem7Button
        {
            get
            {
                if ((this.mUIItem7Button == null))
                {
                    this.mUIItem7Button = new WinButton(this);
                    #region Search Criteria
                    this.mUIItem7Button.SearchProperties[WinButton.PropertyNames.Name] = "7";
                    this.mUIItem7Button.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIItem7Button;
            }
        }
        
        public WinButton UIItem4Button
        {
            get
            {
                if ((this.mUIItem4Button == null))
                {
                    this.mUIItem4Button = new WinButton(this);
                    #region Search Criteria
                    this.mUIItem4Button.SearchProperties[WinButton.PropertyNames.Name] = "4";
                    this.mUIItem4Button.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIItem4Button;
            }
        }
        
        public WinButton UIItem1Button
        {
            get
            {
                if ((this.mUIItem1Button == null))
                {
                    this.mUIItem1Button = new WinButton(this);
                    #region Search Criteria
                    this.mUIItem1Button.SearchProperties[WinButton.PropertyNames.Name] = "1";
                    this.mUIItem1Button.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIItem1Button;
            }
        }
        
        public WinButton UIItem0Button
        {
            get
            {
                if ((this.mUIItem0Button == null))
                {
                    this.mUIItem0Button = new WinButton(this);
                    #region Search Criteria
                    this.mUIItem0Button.SearchProperties[WinButton.PropertyNames.Name] = "0";
                    this.mUIItem0Button.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIItem0Button;
            }
        }
        
        public WinButton UIItem8Button
        {
            get
            {
                if ((this.mUIItem8Button == null))
                {
                    this.mUIItem8Button = new WinButton(this);
                    #region Search Criteria
                    this.mUIItem8Button.SearchProperties[WinButton.PropertyNames.Name] = "8";
                    this.mUIItem8Button.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIItem8Button;
            }
        }
        
        public WinButton UIItem5Button
        {
            get
            {
                if ((this.mUIItem5Button == null))
                {
                    this.mUIItem5Button = new WinButton(this);
                    #region Search Criteria
                    this.mUIItem5Button.SearchProperties[WinButton.PropertyNames.Name] = "5";
                    this.mUIItem5Button.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIItem5Button;
            }
        }
        
        public WinButton UIItem2Button
        {
            get
            {
                if ((this.mUIItem2Button == null))
                {
                    this.mUIItem2Button = new WinButton(this);
                    #region Search Criteria
                    this.mUIItem2Button.SearchProperties[WinButton.PropertyNames.Name] = "2";
                    this.mUIItem2Button.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIItem2Button;
            }
        }
        
        public WinButton UIItem9Button
        {
            get
            {
                if ((this.mUIItem9Button == null))
                {
                    this.mUIItem9Button = new WinButton(this);
                    #region Search Criteria
                    this.mUIItem9Button.SearchProperties[WinButton.PropertyNames.Name] = "9";
                    this.mUIItem9Button.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIItem9Button;
            }
        }
        
        public WinButton UIItem6Button
        {
            get
            {
                if ((this.mUIItem6Button == null))
                {
                    this.mUIItem6Button = new WinButton(this);
                    #region Search Criteria
                    this.mUIItem6Button.SearchProperties[WinButton.PropertyNames.Name] = "6";
                    this.mUIItem6Button.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIItem6Button;
            }
        }
        
        public WinButton UIItem3Button
        {
            get
            {
                if ((this.mUIItem3Button == null))
                {
                    this.mUIItem3Button = new WinButton(this);
                    #region Search Criteria
                    this.mUIItem3Button.SearchProperties[WinButton.PropertyNames.Name] = "3";
                    this.mUIItem3Button.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIItem3Button;
            }
        }
        
        public WinButton UICButton
        {
            get
            {
                if ((this.mUICButton == null))
                {
                    this.mUICButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICButton.SearchProperties[WinButton.PropertyNames.Name] = "C";
                    this.mUICButton.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUICButton;
            }
        }
        
        public WinButton UIItemButton
        {
            get
            {
                if ((this.mUIItemButton == null))
                {
                    this.mUIItemButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIItemButton.SearchProperties[WinButton.PropertyNames.Name] = "+";
                    this.mUIItemButton.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIItemButton;
            }
        }
        
        public WinButton UIItemButton1
        {
            get
            {
                if ((this.mUIItemButton1 == null))
                {
                    this.mUIItemButton1 = new WinButton(this);
                    #region Search Criteria
                    this.mUIItemButton1.SearchProperties[WinButton.PropertyNames.Name] = "-";
                    this.mUIItemButton1.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIItemButton1;
            }
        }
        
        public WinButton UIItemButton2
        {
            get
            {
                if ((this.mUIItemButton2 == null))
                {
                    this.mUIItemButton2 = new WinButton(this);
                    #region Search Criteria
                    this.mUIItemButton2.SearchProperties[WinButton.PropertyNames.Name] = "*";
                    this.mUIItemButton2.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIItemButton2;
            }
        }
        
        public WinButton UIItemButton3
        {
            get
            {
                if ((this.mUIItemButton3 == null))
                {
                    this.mUIItemButton3 = new WinButton(this);
                    #region Search Criteria
                    this.mUIItemButton3.SearchProperties[WinButton.PropertyNames.Name] = "/";
                    this.mUIItemButton3.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIItemButton3;
            }
        }
        
        public WinButton UIItemButton4
        {
            get
            {
                if ((this.mUIItemButton4 == null))
                {
                    this.mUIItemButton4 = new WinButton(this);
                    #region Search Criteria
                    this.mUIItemButton4.SearchProperties[WinButton.PropertyNames.Name] = "=";
                    this.mUIItemButton4.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIItemButton4;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIItem7Button;
        
        private WinButton mUIItem4Button;
        
        private WinButton mUIItem1Button;
        
        private WinButton mUIItem0Button;
        
        private WinButton mUIItem8Button;
        
        private WinButton mUIItem5Button;
        
        private WinButton mUIItem2Button;
        
        private WinButton mUIItem9Button;
        
        private WinButton mUIItem6Button;
        
        private WinButton mUIItem3Button;
        
        private WinButton mUICButton;
        
        private WinButton mUIItemButton;
        
        private WinButton mUIItemButton1;
        
        private WinButton mUIItemButton2;
        
        private WinButton mUIItemButton3;
        
        private WinButton mUIItemButton4;
        #endregion
    }
}
